soundpilgrim/musicblog/urls.py
from django.conf.urls import patterns, url

from musicblog import views

urlpatterns = patterns('',
    url(r'^chill/', views.chill, name='chill'),
    url(r'^funky/', views.funky, name='funky'),
    url(r'^indie/', views.indie, name='indie'),
    url(r'^rap/', views.rap, name='rap'),
    url(r'^party/', views.party, name='party'),
    url(r'^$', views.all_music, name='all_music'),
)

soundpilgrim/soundpilgrim/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'soundpilgrim.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'soundpilgrim.views.home', name='home'),
    url(r'^genre/', include('musicblog.urls', namespace="musicblog")),
    url(r'^admin/', include(admin.site.urls)),
)

soundpilgrim/musicblog/models.py
from django.db import models
import re

class SongCarousel(models.Model):
    song_carousel_title = models.CharField(max_length=200)

    def __unicode__(self):
        return self.song_carousel_title

class Genre(models.Model):
    genre_name = models.CharField('Genre', max_length = 50, null=False)
    short_name = models.CharField('Short Descriptor', max_length=20, null=False)

    def __unicode__(self):
        return self.genre_name

class SongPost(models.Model):
    created_on = models.DateTimeField('Date Created', null=False, editable=True)
    song_title = models.CharField(max_length=200, null=False)
    artist = models.CharField(max_length=200, null=False)
    genre = models.ForeignKey(Genre, null=False)
    soundcloud_url = models.TextField(null=False)
    song_carousel = models.ForeignKey(SongCarousel, blank=True, null=True)

    def is_in_song_carousel(self):
        return self.song_carousel
    is_in_song_carousel.boolean = True
    is_in_song_carousel.short_description = 'In Song Carousel?'

    def save(self, *args, **kwargs):
        self.full_clean()
        super(SongPost, self).save(*args, **kwargs)

    def clean(self, *args, **kwargs):
        self.soundcloud_url = clean_soundcloud_url(self.soundcloud_url)
        super(SongPost, self).clean(*args, **kwargs)

    def __unicode__(self):
        return self.song_title + ' - ' + self.artist + ' (' + unicode(self.genre) + ')'

# Helper functions

def clean_soundcloud_url(old_soundcloud_url):

    iframe_start = '<iframe width="100%" height="100%" scrolling="no" frameborder="no" src="'
    iframe_end = '&amp;auto_play=false&amp;hide_related=true&amp;show_user=false&amp;show_comments=false&amp;visual=true"></iframe>'


    url_segment = re.search(r'src="(.+?)&amp', old_soundcloud_url)
    
    new_soundcloud_url = ""
    if url_segment:

        new_soundcloud_url = iframe_start + url_segment.group(1) + iframe_end
    else:
        new_soundcloud_url = ""

    return new_soundcloud_url 

soundpilgrim/musicblog/views.py
from django.utils import timezone
from django.shortcuts import render, render_to_response, RequestContext
from django.http import HttpResponse

from musicblog.models import SongPost, Genre

def chill(request, template='musicblog/base_genre.html', page_template='musicblog/base_genre_page.html'):
    recent_songposts = get_recent_songposts('Chill') 
    context = {}
    context.update({'genre': "Chill", 'short_genre': 'chill', 'recent_songposts': recent_songposts, 'page_template': page_template, })
    if request.is_ajax():
        template = page_template

    return render_to_response(template, context, context_instance=RequestContext(request))


def funky(request, template='musicblog/base_genre.html', page_template='musicblog/base_genre_page.html'):
    recent_songposts = get_recent_songposts('Funky') 
    context = {}
    context.update({'genre': "Funky", 'short_genre': 'funky', 'recent_songposts': recent_songposts, 'page_template': page_template, })
    if request.is_ajax():
        template = page_template

    return render_to_response(template, context, context_instance=RequestContext(request))

def indie(request, template='musicblog/base_genre.html', page_template='musicblog/base_genre_page.html'):
    recent_songposts = get_recent_songposts('Indie') 
    context = {}
    context.update({'genre': "Indie & Alternative", 'short_genre': 'indie', 'recent_songposts': recent_songposts, 'page_template': page_template, })
    if request.is_ajax():
        template = page_template

    return render_to_response(template, context, context_instance=RequestContext(request))


def rap(request, template='musicblog/base_genre.html', page_template='musicblog/base_genre_page.html'):
    recent_songposts = get_recent_songposts('Rap') 
    context = {}
    context.update({'genre': "Rap", 'short_genre': 'rap', 'recent_songposts': recent_songposts, 'page_template': page_template, })
    if request.is_ajax():
        template = page_template

    return render_to_response(template, context, context_instance=RequestContext(request))


def party(request, template='musicblog/base_genre.html', page_template='musicblog/base_genre_page.html'):
    recent_songposts = get_recent_songposts('Party') 
    context = {}
    context.update({'genre': "Party", 'short_genre': 'party', 'recent_songposts': recent_songposts, 'page_template': page_template, })
    if request.is_ajax():
        template = page_template

    return render_to_response(template, context, context_instance=RequestContext(request))
    

def all_music(request, template='musicblog/base_genre.html', page_template='musicblog/base_genre_page.html'):
    recent_songposts = get_recent_songposts('All') 
    context = {}
    context.update({'genre': "All Music", 'short_genre': 'all_music', 'recent_songposts': recent_songposts, 'page_template': page_template, })
    if request.is_ajax():
        template = page_template

    return render_to_response(template, context, context_instance=RequestContext(request))

def get_recent_songposts(genre):
    if genre != 'All':
        g = Genre.objects.get(genre_name__contains=genre)
        recent_songposts = g.songpost_set.filter(created_on__lte=timezone.now()).order_by('-created_on')
    else:
        recent_songposts = SongPost.objects.all().order_by('-created_on')
    return recent_songposts

soundpilgrim/soundpilgrim/views.py
from django.shortcuts import render

def home(request):
    context = {'is_home': True}
    return render(request, 'index.html', context)

soundpilgrim/musicblog/templates/musicblog/base_genre.html
{% extends "base.html" %}

{% load static %}

{% block title %}{{ genre }}{% endblock title %}

{% block body_classes %}no-sidebar {{ short_genre }} feedPage{% endblock body_classes %}

{% block header_id %}feedHeader{% endblock header_id %}

{% block body_content %}

<div id ="genreWrapper" class="wrapper style1">
	<div class="container">
		<div class="row">
			<div class="12u skel-cell-important" id="content">


{% if recent_songposts %}
<div class="endless_page_template">
{% include page_template %}
</div>
{% else %}
    <h2>Looks like there aren't any posts...</h2>
{% endif %}


			</div>
		</div>
	</div>
</div>

{% endblock body_content %}

{% block bottom_scripts %}
{{ block.super }}
<script type="text/javascript" src="{% static "js/sc_api.js" %}"></script>
<script type="text/javascript" src="{% static "js/continuous_play.js" %}"></script>
<script>
  new_widgets = 0;
  new_index = 0;
  continuousPlayEval();
</script>
<script src="{{ STATIC_URL }}endless_pagination/js/endless_on_scroll.js"></script>
<script src="{{ STATIC_URL }}endless_pagination/js/endless-pagination.js"></script>
<script>
continuousPlayEval();

$.endlessPaginate({
		paginateOnScroll: true,
		paginateOnScrollChunkSize: 6,
		paginateOnScrollMargin: 200,
    onCompleted: function(context, fragment) {
        console.log("Loaded!");
        continuousPlayEval();
    },
});
</script>
{% endblock bottom_scripts %}

soundpilgrim/musicblog/templates/musicblog/base_genre_page.html
{% load endless %}

{% lazy_paginate 10 recent_songposts %}
{% for post in recent_songposts %}
<div class="post {{ post.genre.short_name }} 6u">
    <h1 class="post_title">{{ post.song_title }}</h1>
    <h3 class="post_artist">{{ post.artist }}</h3>
	<div class="genre_color">
	</div>
	<div class="post_music 12u">
		{{ post.soundcloud_url|safe }}
	</div>	
</div>	
{% endfor %}
{% show_more %}

soundpilgrim/templates/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
	<head>
	<title>Sound Pilgrim | {% block title %}Welcome{% endblock title %}</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />

		<!--[if lte IE 8]><script src="js/html5shiv.js"></script><![endif]-->
		<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600" rel="stylesheet" type="text/css" />
		<link href='http://fonts.googleapis.com/css?family=Amatic+SC&text=Indie%20%26%20Alternative' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=League+Script&text=Chill' rel='stylesheet'  type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Reenie+Beanie&text=Rap' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Fredoka+One&text=Party' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Codystar&text=Funky' rel='stylesheet' type='text/css'>
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie8.css" /><![endif]-->

		<link rel="stylesheet" href="{% static "css/font-awesome/css/font-awesome.min.css" %}">
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
		<script src="{% static "js/jquery.dropotron.min.js" %}"></script>
		<script src="{% static "js/skel.min.js" %}"></script>
		<script src="{% static "js/skel-panels.min.js" %}"></script>
		<script src="{% static "js/init.js" %}"></script>
		<noscript>
		    <link rel="stylesheet" href="{% static "css/skel-noscript.css" %}" />
		    <link rel="stylesheet" href="{% static "css/style.css" %}" />
		    <link rel="stylesheet" href="{% static "css/style-desktop.css" %}"/>
		    <link rel="stylesheet" href="{% static "css/style-noscript.css" %}"/>
		</noscript>

		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-52061039-1', 'soundpilgrim.com');
		  ga('send', 'pageview');

		</script>
	</head>
	<body class="{% block body_classes %}{% endblock body_classes %} ">

		<!-- Header -->
		<div id="{%block header_id %}feedHeader{% endblock header_id %}">

				<!-- Nav -->
					<nav id="nav">
					    {% if not is_home %}
					    	<a href="{% url 'home' %}" ><i id="home_button" class="fa fa-home"></i></a><br>
					    {% endif %}
					    <ul id="genres">
						<li id="chill"><a href="{% url 'musicblog:chill' %}">Chill</a></li>
						<li id="funky"><a href="{% url 'musicblog:funky' %}">Funky</a></li>
						<li id="indie"><a href="{% url 'musicblog:indie' %}">Indie &amp; Alternative</a></li>
						<li id="rap"><a href="{% url 'musicblog:rap' %}">Rap</a></li>
						<li id="party"><a href="{% url 'musicblog:party' %}">Party</a></li>
					    </ul>
					    <br/>
					    <ul id="allMusicNav">
						<li id="allMusic"><a href="{% url 'musicblog:all_music' %}">All Music</a></li>
					    </ul>
					</nav>
					
					{% block inner_nav %}
					{% endblock inner_nav %}
			</div>

			{% block body_content %}

			{% endblock body_content %}

		<!-- Footer -->
			<div id="footer">
				<div class="container">
					<div class="row">
						<div class="12u">
							<section class="footerBottom">
								<header>
									<span class="dailyQuote">Because good music is worth your time.</span>
								</header>
								<header>
								<ul class="icons">
									<li><a href="https://twitter.com/Sound_Pilgrim"><i class="fa fa-twitter solo"></i></a></li>
									<li><a href="https://www.facebook.com/SoundPilgrim"><i class="fa fa-facebook solo"></i></a></li>
									<li><a href="https://soundcloud.com/sound-pilgrim"><i class="fa fa-soundcloud solo"></i></a></li>
								</ul>
								</header>
							</section>
						<!-- Copyright -->
							<div class="names">
								<ul class="menu">
									<li>Jake</li>
									<li>Arjun</li>
									<li>John</li>
									<li>Mayank</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>

	{% block bottom_scripts %}
	{% endblock bottom_scripts %}
	</body>
</html>

soundpilgrim/templates/index.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock title %}

{% block body_classes %}homepage{% endblock body_classes %}

{% block header_id %}header{% endblock header_id %}

{% block inner_nav %}

<div class="inner">
	<footer>
		<a href="#welcome" class="button circled moreButton">More</a>
	</footer>
</div>

{% endblock inner_nav %}

{% block body_content %}

<div id="welcome">
	<h2>Welcome To <strong>Sound Pilgrim</strong>.</h2>
	<span class="byline">
		Sound Pilgrim gives you access to amazing music through a beautifully simplistic experience.  Long posts littered with text have no place here...  We prefer to let the music speak for itself.  At Sound Pilgrim, we only have one rule:  If we like it, we'll post it.  Because good music is worth your time.
	</span>
	
</div>

{% endblock body_content %}